CREATE TABLE gp_Highlight
(	
	id CHAR(32) NOT NULL,
	category VARCHAR(100) NOT NULL,
	title VARCHAR(255) NOT NULL,
	image CHAR(32) NULL,
	introduction VARCHAR(400) NOT NULL,
	position INT NOT NULL,
	type INT NOT NULL,
	url  VARCHAR(255) NULL,
	clickPopup INT DEFAULT 0 NOT NULL,
	content LONGTEXT NULL,
	documentId CHAR(32) NULL,
	CONSTRAINT GP_PK_HIGHLIGHT PRIMARY KEY (id)
) 
ENGINE=InnoDB DEFAULT CHARSET=utf8;