CREATE TABLE gp_Column
(	
	id CHAR(32) NOT NULL,
	title VARCHAR(255) NOT NULL,
	columnist VARCHAR(255) NOT NULL,
	image CHAR(32) NULL,
	description LONGTEXT NOT NULL,
	CONSTRAINT GP_PK_COLUMN PRIMARY KEY (id)
) 
ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE gp_ColumnContent
(	
	id CHAR(32) NOT NULL,
	title VARCHAR(255) NOT NULL,
	columnistId CHAR(32) NOT NULL,
	introduction LONGTEXT NOT NULL,
	introductionImage CHAR(32) NULL,
	content LONGTEXT NOT NULL,
	CONSTRAINT GP_PK_COLUMN_CONTENT PRIMARY KEY (id)
) 
ENGINE=InnoDB DEFAULT CHARSET=utf8;

