CREATE TABLE gp_SimpleText
(	
	id CHAR(32) NOT NULL,
	title VARCHAR(255) NOT NULL,
	introductionImage CHAR(32) NULL,
	introduction LONGTEXT NULL,
	content LONGTEXT NOT NULL,
	CONSTRAINT GP_PK_SIMPLE_TEXT PRIMARY KEY (id)
) 
ENGINE=InnoDB DEFAULT CHARSET=utf8;